#!/usr/bin/env bash 
echo "dont forget to activate your env" 

python /Users/maltak/Code/MultiChoice2ExtractiveQA/Notebooks/f1_em_eval.py --input_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/All/RefPredPairs/MSA-P_ars-Q.tsv --output_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/All/RefPredPairs_Processed/MSA-P_ars-Q.tsv --language arabic
python /Users/maltak/Code/MultiChoice2ExtractiveQA/Notebooks/f1_em_eval.py --input_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/All/RefPredPairs/MSA-P_EN-Q.tsv --output_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/All/RefPredPairs_Processed/MSA-P_EN-Q.tsv --language arabic
python /Users/maltak/Code/MultiChoice2ExtractiveQA/Notebooks/f1_em_eval.py --input_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/All/RefPredPairs/EN-P_ars-Q.tsv --output_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/All/RefPredPairs_Processed/EN-P_ars-Q.tsv --language english
python /Users/maltak/Code/MultiChoice2ExtractiveQA/Notebooks/f1_em_eval.py --input_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/All/RefPredPairs/EN-P_MSA-Q.tsv --output_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/All/RefPredPairs_Processed/EN-P_MSA-Q.tsv --language english
python /Users/maltak/Code/MultiChoice2ExtractiveQA/Notebooks/f1_em_eval.py --input_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/All/RefPredPairs/MSA-P_ary-Q.tsv --output_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/All/RefPredPairs_Processed/MSA-P_ary-Q.tsv --language arabic
python /Users/maltak/Code/MultiChoice2ExtractiveQA/Notebooks/f1_em_eval.py --input_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/All/RefPredPairs/MSA-P_MSA-Q.tsv --output_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/All/RefPredPairs_Processed/MSA-P_MSA-Q.tsv --language arabic
python /Users/maltak/Code/MultiChoice2ExtractiveQA/Notebooks/f1_em_eval.py --input_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/All/RefPredPairs/EN-P_ary-Q.tsv --output_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/All/RefPredPairs_Processed/EN-P_ary-Q.tsv --language english
python /Users/maltak/Code/MultiChoice2ExtractiveQA/Notebooks/f1_em_eval.py --input_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/All/RefPredPairs/EN-P_EN-Q.tsv --output_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/All/RefPredPairs_Processed/EN-P_EN-Q.tsv --language english
python /Users/maltak/Code/MultiChoice2ExtractiveQA/Notebooks/f1_em_eval.py --input_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/All/RefPredPairs/EN-P_apc-Q.tsv --output_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/All/RefPredPairs_Processed/EN-P_apc-Q.tsv --language english
python /Users/maltak/Code/MultiChoice2ExtractiveQA/Notebooks/f1_em_eval.py --input_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/All/RefPredPairs/MSA-P_arz-Q.tsv --output_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/All/RefPredPairs_Processed/MSA-P_arz-Q.tsv --language arabic
python /Users/maltak/Code/MultiChoice2ExtractiveQA/Notebooks/f1_em_eval.py --input_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/All/RefPredPairs/MSA-P_acm-Q.tsv --output_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/All/RefPredPairs_Processed/MSA-P_acm-Q.tsv --language arabic
python /Users/maltak/Code/MultiChoice2ExtractiveQA/Notebooks/f1_em_eval.py --input_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/All/RefPredPairs/EN-P_arz-Q.tsv --output_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/All/RefPredPairs_Processed/EN-P_arz-Q.tsv --language english
python /Users/maltak/Code/MultiChoice2ExtractiveQA/Notebooks/f1_em_eval.py --input_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/All/RefPredPairs/EN-P_acm-Q.tsv --output_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/All/RefPredPairs_Processed/EN-P_acm-Q.tsv --language english
python /Users/maltak/Code/MultiChoice2ExtractiveQA/Notebooks/f1_em_eval.py --input_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/All/RefPredPairs/MSA-P_apc-Q.tsv --output_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/All/RefPredPairs_Processed/MSA-P_apc-Q.tsv --language arabic
python /Users/maltak/Code/MultiChoice2ExtractiveQA/Notebooks/f1_em_eval.py --input_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/NoBB/RefPredPairs/MSA-P_ars-Q.tsv --output_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/NoBB/RefPredPairs_Processed/MSA-P_ars-Q.tsv --language arabic
python /Users/maltak/Code/MultiChoice2ExtractiveQA/Notebooks/f1_em_eval.py --input_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/NoBB/RefPredPairs/MSA-P_EN-Q.tsv --output_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/NoBB/RefPredPairs_Processed/MSA-P_EN-Q.tsv --language arabic
python /Users/maltak/Code/MultiChoice2ExtractiveQA/Notebooks/f1_em_eval.py --input_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/NoBB/RefPredPairs/EN-P_ars-Q.tsv --output_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/NoBB/RefPredPairs_Processed/EN-P_ars-Q.tsv --language english
python /Users/maltak/Code/MultiChoice2ExtractiveQA/Notebooks/f1_em_eval.py --input_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/NoBB/RefPredPairs/EN-P_MSA-Q.tsv --output_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/NoBB/RefPredPairs_Processed/EN-P_MSA-Q.tsv --language english
python /Users/maltak/Code/MultiChoice2ExtractiveQA/Notebooks/f1_em_eval.py --input_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/NoBB/RefPredPairs/MSA-P_ary-Q.tsv --output_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/NoBB/RefPredPairs_Processed/MSA-P_ary-Q.tsv --language arabic
python /Users/maltak/Code/MultiChoice2ExtractiveQA/Notebooks/f1_em_eval.py --input_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/NoBB/RefPredPairs/MSA-P_MSA-Q.tsv --output_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/NoBB/RefPredPairs_Processed/MSA-P_MSA-Q.tsv --language arabic
python /Users/maltak/Code/MultiChoice2ExtractiveQA/Notebooks/f1_em_eval.py --input_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/NoBB/RefPredPairs/EN-P_ary-Q.tsv --output_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/NoBB/RefPredPairs_Processed/EN-P_ary-Q.tsv --language english
python /Users/maltak/Code/MultiChoice2ExtractiveQA/Notebooks/f1_em_eval.py --input_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/NoBB/RefPredPairs/EN-P_EN-Q.tsv --output_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/NoBB/RefPredPairs_Processed/EN-P_EN-Q.tsv --language english
python /Users/maltak/Code/MultiChoice2ExtractiveQA/Notebooks/f1_em_eval.py --input_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/NoBB/RefPredPairs/EN-P_apc-Q.tsv --output_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/NoBB/RefPredPairs_Processed/EN-P_apc-Q.tsv --language english
python /Users/maltak/Code/MultiChoice2ExtractiveQA/Notebooks/f1_em_eval.py --input_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/NoBB/RefPredPairs/MSA-P_arz-Q.tsv --output_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/NoBB/RefPredPairs_Processed/MSA-P_arz-Q.tsv --language arabic
python /Users/maltak/Code/MultiChoice2ExtractiveQA/Notebooks/f1_em_eval.py --input_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/NoBB/RefPredPairs/MSA-P_acm-Q.tsv --output_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/NoBB/RefPredPairs_Processed/MSA-P_acm-Q.tsv --language arabic
python /Users/maltak/Code/MultiChoice2ExtractiveQA/Notebooks/f1_em_eval.py --input_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/NoBB/RefPredPairs/EN-P_arz-Q.tsv --output_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/NoBB/RefPredPairs_Processed/EN-P_arz-Q.tsv --language english
python /Users/maltak/Code/MultiChoice2ExtractiveQA/Notebooks/f1_em_eval.py --input_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/NoBB/RefPredPairs/EN-P_acm-Q.tsv --output_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/NoBB/RefPredPairs_Processed/EN-P_acm-Q.tsv --language english
python /Users/maltak/Code/MultiChoice2ExtractiveQA/Notebooks/f1_em_eval.py --input_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/NoBB/RefPredPairs/MSA-P_apc-Q.tsv --output_file /Users/maltak/Code/MultiChoice2ExtractiveQA/Results/normalizedScore/NoBB/RefPredPairs_Processed/MSA-P_apc-Q.tsv --language arabic
